version: '3.9'

services:
  db:
    image: postgres
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  project:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project
    ports:
      - "8000:8000"
    command: bash -c "python manage.py migrate --no-input && python install.py && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - .:/project
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: