# Generated by Django 5.0.6 on 2024-06-19 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_training_instructor_alter_training_students'),
        ('event', '0002_alter_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.training'),
        ),
    ]
