# Generated by Django 5.0.6 on 2024-06-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_grade'),
        ('education', '0003_sign'),
    ]

    operations = [
    ]
