# Generated by Django 5.0.6 on 2024-06-20 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_training'),
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign',
            name='instructor',
        ),
        migrations.AddField(
            model_name='sign',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sign_event', to='event.event'),
        ),
    ]
