# Generated by Django 5.0.6 on 2024-06-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'CFA'), (2, 'Student'), (3, 'Instructor')], default=2),
        ),
    ]
