# Generated by Django 5.0.6 on 2024-06-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Student'), (2, 'Instructor'), (3, 'CFA')], default=1),
        ),
    ]
