# Generated by Django 5.0.6 on 2024-06-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_cfa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_password_token',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
